//! §7.4 / §-1.5 / §114 NDJSON trace format: schema + parser (M11.1; D11.5).
//!
//! One JSON object per line (NDJSON). The outer shape is `serde(tag =
//! "type", rename_all = "snake_case")`; every line names its own kind. Every
//! event carries `at: u64` (logical milliseconds, monotone nondecreasing)
//! EXCEPT `trace_header`, which is corpus metadata (mandatory line 1) rather
//! than a timed occurrence.
//!
//! D11.5 (frozen): the parser REJECTS unknown fields
//! (`#[serde(deny_unknown_fields)]` on every variant) — a corpus defect (a
//! stray key, a typo'd field name) fails loudly instead of silently dropping
//! data (v4 §7.4; POLICY.md §5: "a trace whose provenance cannot be stated
//! does not enter the corpus" generalizes to "a trace that cannot be
//! precisely parsed does not enter the corpus").

use serde::{Deserialize, Serialize};

pub use liminal_daemon::scenario::SetupGraph;

/// `trace_header.consent` (R4 §11.5: editor sessions require a stated
/// consent/anonymization status before entering any corpus).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Consent {
    /// A real editor session, consented and anonymized (POLICY.md §5).
    ConsentedAnonymized,
    /// Generated by a harness (e.g. `tracegen`), not captured from a human.
    Synthetic,
    /// An imported real public-repository Git history.
    PublicGit,
}

/// Root-cause category on a root-cause-capable event (D11.3: reuses D05.5's
/// `<category>:<key>` grammar at the trace level). This is the trace
/// format's OWN category namespace — distinct from the daemon's internal
/// Reconciliation-Queue categories (`conflict | identity | offline |
/// ambiguity | undo`, D05.5) — though the `<category>:<key>` shape matches.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CauseCategory {
    /// `file_change_external` from an uninstrumented foreign tool.
    Foreign,
    /// `file_change_external` / `formatter_rewrite` from a formatter.
    Formatter,
    /// `git_op` / its accompanying `file_change_external` delivery events.
    Git,
    /// `holder_unavailable`.
    Holder,
    /// `resolver_observe`.
    Resolver,
}

impl std::fmt::Display for CauseCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            CauseCategory::Foreign => "foreign",
            CauseCategory::Formatter => "formatter",
            CauseCategory::Git => "git",
            CauseCategory::Holder => "holder",
            CauseCategory::Resolver => "resolver",
        };
        f.write_str(s)
    }
}

/// `git_op.op`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum GitOpKind {
    /// A commit.
    Commit,
    /// A merge.
    Merge,
    /// A rebase.
    Rebase,
    /// A cherry-pick.
    CherryPick,
    /// A checkout.
    Checkout,
}

/// `buffer_edit.range` — a byte splice `[start, end)` over the buffer's
/// prior content.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EditRange {
    /// Splice start byte offset.
    pub start: u64,
    /// Splice end byte offset.
    pub end: u64,
}

/// `trace_header.setup.files[]`. Deliberately its OWN shape (`{path,
/// contents}`), NOT the M03 scenario `SetupFile` (which uses `text`): the
/// schema table spells `setup.files` out explicitly, matching the trace
/// format's other full-bytes fields (`file_change_external.contents`,
/// `formatter_rewrite.contents`); only `setup.graph` defers to "the M03
/// setup tables" (`SetupGraph` reuse, imported above).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TraceSetupFile {
    /// Workspace-relative path.
    pub path: String,
    /// Full initial file contents (toy scale: UTF-8 text).
    pub contents: String,
}

/// `trace_header.setup`: the workspace a trace replays against.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TraceSetup {
    /// Files to create before replay.
    #[serde(default)]
    pub files: Vec<TraceSetupFile>,
    /// Graph-native subjects to create before replay (M03 setup tables).
    #[serde(default)]
    pub graph: Vec<SetupGraph>,
}

/// One NDJSON trace line — thirteen event types (v4 §7.4 / §-1.5). D11.5:
/// every variant is `deny_unknown_fields`, so an unrecognized field on any
/// line is a hard parse error, never a silent drop.
///
/// No `PartialEq` derive: `TraceHeader` carries `TraceSetup`, which reuses
/// the M03 `SetupGraph` (deliberately lenient, no `PartialEq` of its own —
/// see `liminal_daemon::scenario`); tests compare individual fields instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case", deny_unknown_fields)]
pub enum TraceEvent {
    /// Mandatory line 1: provenance, consent, and the replay setup.
    TraceHeader {
        /// Schema version; currently always `1`.
        version: u32,
        /// Stable id for this trace.
        trace_id: String,
        /// Where the trace came from (e.g. `"m7-script:<name>"`).
        source: String,
        /// The tool that captured/generated it.
        capture_tool: String,
        /// Consent / anonymization / provenance status.
        consent: Consent,
        /// The Jurisdiction profile this trace measures.
        profile: String,
        /// The workspace to build before replay.
        setup: TraceSetup,
    },
    /// Explicit session start.
    SessionOpen {
        /// Logical ms.
        at: u64,
        /// Session id.
        session: String,
        /// Client id.
        client: String,
    },
    /// Explicit session end.
    SessionClose {
        /// Logical ms.
        at: u64,
        /// Session id.
        session: String,
    },
    /// A buffer is opened — one Jurisdiction-sensitive read (Algorithm A).
    BufferOpen {
        /// Logical ms.
        at: u64,
        /// Session id.
        session: String,
        /// Client id.
        client: String,
        /// Buffer id.
        buffer: String,
        /// Workspace-relative path the buffer covers.
        path: String,
    },
    /// A raw keystroke-level edit; coalesced into semantic transactions by
    /// D11.1 before counting (Algorithm A).
    BufferEdit {
        /// Logical ms.
        at: u64,
        /// Session id.
        session: String,
        /// Buffer id.
        buffer: String,
        /// The byte splice this edit replaces.
        range: EditRange,
        /// The inserted text.
        insert: String,
    },
    /// Promotion (save) — a repair from the buffer Overlay to the file
    /// Holder (v4 §7.5).
    Save {
        /// Logical ms.
        at: u64,
        /// Session id.
        session: String,
        /// Buffer id.
        buffer: String,
    },
    /// A file changed outside the daemon's own write path (foreign tool,
    /// formatter, or the byte-delivery half of a `git_op`).
    FileChangeExternal {
        /// Logical ms.
        at: u64,
        /// Workspace-relative path.
        path: String,
        /// Full new bytes (toy scale: UTF-8 text).
        contents: String,
        /// Root-cause category.
        cause_category: CauseCategory,
        /// Root-cause key (D11.3/D05.5 grammar).
        cause_key: String,
    },
    /// A Git operation (M07 hermetic runbook replay).
    GitOp {
        /// Logical ms.
        at: u64,
        /// The Git operation kind.
        op: GitOpKind,
        /// Every file this operation touched.
        files: Vec<String>,
        /// Always `Git` (D11.3/D05.5 grammar).
        cause_category: CauseCategory,
        /// Root-cause key, `"<op>@<at>"`.
        cause_key: String,
    },
    /// A deterministic foreign formatter/rich-tool rewrite.
    FormatterRewrite {
        /// Logical ms.
        at: u64,
        /// Workspace-relative path.
        path: String,
        /// Full new bytes (toy scale: UTF-8 text).
        contents: String,
        /// The formatter/tool name.
        tool: String,
        /// Always `Formatter` (D11.3/D05.5 grammar).
        cause_category: CauseCategory,
        /// Root-cause key, `"<tool>@<at>"`.
        cause_key: String,
    },
    /// A Holder (file, in the external-file profile) becomes unavailable.
    HolderUnavailable {
        /// Logical ms.
        at: u64,
        /// The Holder identifier (Phase -1: the file path, D05.1).
        holder: String,
        /// Always `Holder` (D11.3/D05.5 grammar).
        cause_category: CauseCategory,
        /// Root-cause key, `"<holder>@<at>"`.
        cause_key: String,
    },
    /// A Holder becomes available again — triggers Overlay reconciliation
    /// (Algorithm A: "1 per Overlay reconciliation attempted").
    HolderAvailable {
        /// Logical ms.
        at: u64,
        /// The Holder identifier (Phase -1: the file path, D05.1).
        holder: String,
    },
    /// An external resolver reports an observation.
    ResolverObserve {
        /// Logical ms.
        at: u64,
        /// The resolver/source id.
        source: String,
        /// The observed value (toy scale: opaque text).
        observed: String,
        /// Always `Resolver` (D11.3/D05.5 grammar).
        cause_category: CauseCategory,
        /// Root-cause key, `"<source>@<at>"`.
        cause_key: String,
    },
    /// A pure logical-time jump (no other effect). A jump spanning ≥30
    /// minutes participates in D11.2 session-timeout accounting.
    ClockAdvance {
        /// Logical ms — the new logical time.
        at: u64,
    },
}

impl TraceEvent {
    /// This event's logical timestamp. `None` only for `TraceHeader`, which
    /// is corpus metadata rather than a timed occurrence.
    #[must_use]
    pub fn at(&self) -> Option<u64> {
        match self {
            TraceEvent::TraceHeader { .. } => None,
            TraceEvent::SessionOpen { at, .. }
            | TraceEvent::SessionClose { at, .. }
            | TraceEvent::BufferOpen { at, .. }
            | TraceEvent::BufferEdit { at, .. }
            | TraceEvent::Save { at, .. }
            | TraceEvent::FileChangeExternal { at, .. }
            | TraceEvent::GitOp { at, .. }
            | TraceEvent::FormatterRewrite { at, .. }
            | TraceEvent::HolderUnavailable { at, .. }
            | TraceEvent::HolderAvailable { at, .. }
            | TraceEvent::ResolverObserve { at, .. }
            | TraceEvent::ClockAdvance { at } => Some(*at),
        }
    }

    /// The `(cause_category, cause_key)` pair (D11.3), for the five
    /// root-cause-capable event kinds only.
    #[must_use]
    pub fn cause(&self) -> Option<(CauseCategory, &str)> {
        match self {
            TraceEvent::FileChangeExternal {
                cause_category,
                cause_key,
                ..
            }
            | TraceEvent::GitOp {
                cause_category,
                cause_key,
                ..
            }
            | TraceEvent::FormatterRewrite {
                cause_category,
                cause_key,
                ..
            }
            | TraceEvent::HolderUnavailable {
                cause_category,
                cause_key,
                ..
            }
            | TraceEvent::ResolverObserve {
                cause_category,
                cause_key,
                ..
            } => Some((*cause_category, cause_key.as_str())),
            _ => None,
        }
    }

    /// The `session` field carried by session/buffer-scoped events. `None`
    /// for workspace-stream events, which attach to sessions by time
    /// instead (D11.2).
    #[must_use]
    pub fn session(&self) -> Option<&str> {
        match self {
            TraceEvent::SessionOpen { session, .. }
            | TraceEvent::SessionClose { session, .. }
            | TraceEvent::BufferOpen { session, .. }
            | TraceEvent::BufferEdit { session, .. }
            | TraceEvent::Save { session, .. } => Some(session.as_str()),
            _ => None,
        }
    }

    /// Whether this is the mandatory `trace_header` line.
    #[must_use]
    pub fn is_header(&self) -> bool {
        matches!(self, TraceEvent::TraceHeader { .. })
    }

    /// The `type` tag, for diagnostics.
    #[must_use]
    pub fn type_tag(&self) -> &'static str {
        match self {
            TraceEvent::TraceHeader { .. } => "trace_header",
            TraceEvent::SessionOpen { .. } => "session_open",
            TraceEvent::SessionClose { .. } => "session_close",
            TraceEvent::BufferOpen { .. } => "buffer_open",
            TraceEvent::BufferEdit { .. } => "buffer_edit",
            TraceEvent::Save { .. } => "save",
            TraceEvent::FileChangeExternal { .. } => "file_change_external",
            TraceEvent::GitOp { .. } => "git_op",
            TraceEvent::FormatterRewrite { .. } => "formatter_rewrite",
            TraceEvent::HolderUnavailable { .. } => "holder_unavailable",
            TraceEvent::HolderAvailable { .. } => "holder_available",
            TraceEvent::ResolverObserve { .. } => "resolver_observe",
            TraceEvent::ClockAdvance { .. } => "clock_advance",
        }
    }
}

/// The only schema version the parser accepts today.
const SUPPORTED_VERSION: u32 = 1;

/// A trace parse failure (D11.5: unknown fields — and every other schema
/// defect — are hard errors, never a silent drop; corpus defects fail
/// loudly).
#[derive(Debug, thiserror::Error)]
pub enum TraceParseError {
    /// Line `line` failed to deserialize as a `TraceEvent`.
    #[error("line {line}: {source}")]
    Json {
        /// 1-based line number.
        line: usize,
        /// The underlying serde error.
        #[source]
        source: serde_json::Error,
    },
    /// The trace had no lines at all.
    #[error("empty trace: a trace_header must be line 1")]
    Empty,
    /// Line 1 was not `trace_header`.
    #[error(
        "line 1 is `{found}`, not `trace_header` — trace_header is mandatory and must be first"
    )]
    MissingHeader {
        /// The tag actually found on line 1.
        found: &'static str,
    },
    /// A later line repeated `trace_header`.
    #[error("line {line}: a second trace_header is not permitted (line 1 is the only header)")]
    DuplicateHeader {
        /// 1-based line number of the offending duplicate.
        line: usize,
    },
    /// `trace_header.version` was not the one supported version.
    #[error("trace_header.version {found} is not the only supported version ({SUPPORTED_VERSION})")]
    UnsupportedVersion {
        /// The version actually found.
        found: u32,
    },
}

/// A fully parsed trace: the mandatory header, plus its ordered event
/// timeline (never including the header line itself).
#[derive(Debug, Clone)]
pub struct Trace {
    /// The line-1 `TraceEvent::TraceHeader`.
    pub header: TraceEvent,
    /// Every subsequent line, in file order.
    pub events: Vec<TraceEvent>,
}

impl Trace {
    /// Parse NDJSON: one `TraceEvent` per non-blank line (D11.5:
    /// `deny_unknown_fields` on every variant). Line 1 MUST be
    /// `trace_header`; no later line may repeat it.
    ///
    /// # Errors
    /// [`TraceParseError`] on any malformed line, a missing/misplaced/
    /// duplicated header, or an unsupported `version`.
    pub fn parse(ndjson: &str) -> Result<Self, TraceParseError> {
        let mut numbered = Vec::new();
        for (idx, line) in ndjson.lines().enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            let event: TraceEvent =
                serde_json::from_str(line).map_err(|source| TraceParseError::Json {
                    line: idx + 1,
                    source,
                })?;
            numbered.push((idx + 1, event));
        }

        let mut iter = numbered.into_iter();
        let Some((_, header)) = iter.next() else {
            return Err(TraceParseError::Empty);
        };
        if !header.is_header() {
            return Err(TraceParseError::MissingHeader {
                found: header.type_tag(),
            });
        }
        if let TraceEvent::TraceHeader { version, .. } = &header
            && *version != SUPPORTED_VERSION
        {
            return Err(TraceParseError::UnsupportedVersion { found: *version });
        }

        let mut events = Vec::new();
        for (line, event) in iter {
            if event.is_header() {
                return Err(TraceParseError::DuplicateHeader { line });
            }
            events.push(event);
        }

        Ok(Trace { header, events })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn header_line() -> String {
        serde_json::to_string(&TraceEvent::TraceHeader {
            version: 1,
            trace_id: "t1".into(),
            source: "unit-test".into(),
            capture_tool: "hand".into(),
            consent: Consent::Synthetic,
            profile: "external-file".into(),
            setup: TraceSetup {
                files: vec![TraceSetupFile {
                    path: "notes.md".into(),
                    contents: "hello\n".into(),
                }],
                graph: Vec::new(),
            },
        })
        .expect("header serializes")
    }

    #[test]
    fn trace_parser_accepts_header_only_trace() {
        let ndjson = header_line();
        let trace = Trace::parse(&ndjson).expect("header-only trace parses");
        assert!(trace.header.is_header());
        assert!(trace.events.is_empty());
    }

    #[test]
    // Long only because it enumerates all 12 non-header event kinds once
    // each — the whole point of the test.
    #[allow(clippy::too_many_lines)]
    fn trace_parser_round_trips_every_event_type() {
        let mut lines = vec![header_line()];
        lines.push(
            serde_json::to_string(&TraceEvent::SessionOpen {
                at: 0,
                session: "s1".into(),
                client: "dev".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::BufferOpen {
                at: 100,
                session: "s1".into(),
                client: "dev".into(),
                buffer: "b1".into(),
                path: "notes.md".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::BufferEdit {
                at: 200,
                session: "s1".into(),
                buffer: "b1".into(),
                range: EditRange { start: 0, end: 0 },
                insert: "hi".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::Save {
                at: 300,
                session: "s1".into(),
                buffer: "b1".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::FileChangeExternal {
                at: 400,
                path: "notes.md".into(),
                contents: "hi\n".into(),
                cause_category: CauseCategory::Foreign,
                cause_key: "foreign@400".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::GitOp {
                at: 500,
                op: GitOpKind::CherryPick,
                files: vec!["notes.md".into()],
                cause_category: CauseCategory::Git,
                cause_key: "cherry-pick@500".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::FormatterRewrite {
                at: 600,
                path: "notes.md".into(),
                contents: "hi\n".into(),
                tool: "prettier".into(),
                cause_category: CauseCategory::Formatter,
                cause_key: "prettier@600".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::HolderUnavailable {
                at: 700,
                holder: "notes.md".into(),
                cause_category: CauseCategory::Holder,
                cause_key: "notes.md@700".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::HolderAvailable {
                at: 800,
                holder: "notes.md".into(),
            })
            .unwrap(),
        );
        lines.push(
            serde_json::to_string(&TraceEvent::ResolverObserve {
                at: 900,
                source: "lsp".into(),
                observed: "ok".into(),
                cause_category: CauseCategory::Resolver,
                cause_key: "lsp@900".into(),
            })
            .unwrap(),
        );
        lines.push(serde_json::to_string(&TraceEvent::ClockAdvance { at: 1000 }).unwrap());
        lines.push(
            serde_json::to_string(&TraceEvent::SessionClose {
                at: 1100,
                session: "s1".into(),
            })
            .unwrap(),
        );

        let trace = Trace::parse(&lines.join("\n")).expect("full round trip parses");
        // 12 non-header lines: every event type except trace_header itself.
        assert_eq!(trace.events.len(), 12);
        assert_eq!(trace.events[0].type_tag(), "session_open");
        assert_eq!(trace.events.last().unwrap().type_tag(), "session_close");
    }

    #[test]
    fn trace_parser_ignores_blank_lines() {
        let ndjson = format!("{}\n\n\n", header_line());
        let trace = Trace::parse(&ndjson).expect("blank lines are skipped");
        assert!(trace.events.is_empty());
    }

    #[test]
    fn trace_parser_rejects_missing_header() {
        let ndjson = serde_json::to_string(&TraceEvent::ClockAdvance { at: 0 }).unwrap();
        let err = Trace::parse(&ndjson).unwrap_err();
        assert!(matches!(err, TraceParseError::MissingHeader { .. }));
    }

    #[test]
    fn trace_parser_rejects_duplicate_header() {
        let ndjson = format!("{}\n{}", header_line(), header_line());
        let err = Trace::parse(&ndjson).unwrap_err();
        assert!(matches!(err, TraceParseError::DuplicateHeader { line: 2 }));
    }

    #[test]
    fn trace_parser_rejects_unsupported_version() {
        let bad = header_line().replace("\"version\":1", "\"version\":2");
        let err = Trace::parse(&bad).unwrap_err();
        assert!(matches!(
            err,
            TraceParseError::UnsupportedVersion { found: 2 }
        ));
    }

    #[test]
    fn trace_parser_rejects_empty_trace() {
        let err = Trace::parse("").unwrap_err();
        assert!(matches!(err, TraceParseError::Empty));
    }

    /// D11.5, unit-level: an unrecognized field on a NON-header line is a
    /// hard parse error. The exit-gate assertion over a full labeled-corpus
    /// style trace lives in `tests/milestones/m11.rs::
    /// trace_parser_rejects_unknown_fields`.
    #[test]
    fn trace_parser_deny_unknown_fields_on_buffer_edit() {
        let bad_line = serde_json::json!({
            "type": "buffer_edit",
            "at": 100,
            "session": "s1",
            "buffer": "b1",
            "range": {"start": 0, "end": 0},
            "insert": "hi",
            "bogus_field": true,
        });
        let ndjson = format!("{}\n{}", header_line(), bad_line);
        let err = Trace::parse(&ndjson).unwrap_err();
        assert!(matches!(err, TraceParseError::Json { line: 2, .. }));
    }

    #[test]
    fn trace_parser_rejects_unknown_top_level_field_on_header() {
        let mut value: serde_json::Value = serde_json::from_str(&header_line()).unwrap();
        value
            .as_object_mut()
            .unwrap()
            .insert("unexpected".into(), serde_json::Value::Bool(true));
        let err = Trace::parse(&value.to_string()).unwrap_err();
        assert!(matches!(err, TraceParseError::Json { line: 1, .. }));
    }

    #[test]
    fn trace_parser_kebab_case_enum_values_round_trip() {
        // `consent` and `git_op.op` use hyphenated values, unlike the
        // snake_case `type` tag — assert the exact wire strings.
        let json = serde_json::to_value(Consent::ConsentedAnonymized).unwrap();
        assert_eq!(json, serde_json::json!("consented-anonymized"));
        let json = serde_json::to_value(GitOpKind::CherryPick).unwrap();
        assert_eq!(json, serde_json::json!("cherry-pick"));
    }
}
